name: qr_utility_app
description: A Flutter QR Code Utility App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # QR generator
  qr_flutter: ^4.1.0

  # QR scanner (Web + Mobile)
  mobile_scanner: ^7.2.0

  image_picker: ^1.0.7

  shared_preferences: ^2.2.2

  # Share button
  share_plus: ^7.2.0

  # Open URLs
  url_launcher: ^6.2.5

  path_provider: ^2.1.2

  # iOS-style icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true